import assert from 'node:assert/strict';
import { contractSchema, contractTypes, normalizeLegacy, validateContract } from '../src/index.mjs';
assert.equal(contractTypes().length,44);
assert.equal(contractSchema('trace').$id,'lumenva.trace.v1');
assert.equal(validateContract('trace',{trace_id:'tr-1',timestamp:new Date().toISOString(),source:'test'}).valid,true);
const invalid=validateContract('trace',{timestamp:'not-a-date'});assert.equal(invalid.valid,false);assert.ok(invalid.errors.some(error=>error.includes('trace_id')));
assert.equal(validateContract('telemetry',{timestamp:new Date().toISOString(),source:'test',measurement_type:'exact',total_tokens:10}).valid,true);
assert.equal(validateContract('telemetry',{timestamp:new Date().toISOString(),source:'test',measurement_type:'fabricated'}).valid,false);
const legacy=normalizeLegacy({task_id:'old-1',executor:'codex',internal_state:'DONE'},'task');assert.equal(legacy.task_id,'old-1');assert.equal(legacy.status,'completed');assert.equal(legacy.measurement_type,'unavailable');
console.log('contract tests: 1 passed');
